### ISSUE TITLE
Unsound behavior for (-)

### ISSUE THREAD

**Issue by larskuhtz** [clash-lang/ghc-typelits-natnormalise#14]
The following program compiles (and runs) fine, while it seems that it shouldn't type check. I think the problem is that the plugin is willing to prove `((n - 1) + 1) ~ n` for `n :: Nat`.

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE UnicodeSyntax #-}
{-# OPTIONS_GHC -fplugin GHC.TypeLits.Normalise #-}
-- {-# OPTIONS_GHC -fplugin GHC.TypeLits.Presburger #-}

module Example where

import GHC.TypeNats
import Numeric.Natural

data Fin (n ∷ Nat) where
    FZ ∷ Fin (n + 1)
    FS ∷ Fin n → Fin (n + 1)

deriving instance Show (Fin n)

f ∷ ∀ n . Natural → Fin n
f n = case n of
    0 → FZ
    x → FS $ f @(n - 1) (x - 1)

fs ∷ [Fin 0]
fs = f <$> [0..]
```

**Comment by christiaanb** [comment]
You are correct, what I should be doing is:

When I see `x - y`, I should add a `y <= x` constraint

**Comment by nanavati** [comment]
It may not be exactly the same problem, but I've also seen unsoundness involving subtraction (starting from version 0.5.5). In my case, the arithmetic in a complex expression involving subtraction goes off the rails (concluding that two expressions that should be equal aren't) and is fixed by adding the right intermediate type signature.

**Comment by christiaanb** [comment]
Trying to fix this on: https://github.com/clash-lang/ghc-typelits-natnormalise/tree/subtraction_implication

**Comment by christiaanb** [comment]
The plugin will now emit a `1 <= n` constraint when it proofs `(n-1)+1~ n`, and the example in the bug report will no consequently no longer type check.

As a result of working on this fix, I actually improved the plugins ability to give proofs about inequalities: https://github.com/clash-lang/ghc-typelits-natnormalise/commit/307ce221e6fd3191b65dfe0bb4200a98b833b629
because otherwise the existing tests would require annoying many inequalities such as:

```haskell
proxyEq2
  :: (1 <= 3*x, 2 <= 2^x, 2^(2*x+1) <= 2^(3*x-1))
  => Proxy (((2 ^ x) - 2) * (2 ^ (x + x)))
  -> Proxy ((2 ^ ((x + (x + x)) - 1)) + ((2 ^ ((x + (x + x)) - 1)) - (2 ^ ((x + x) + 1))))
proxyEq2 = id
```

whereas we can now suffice with:

```haskell
proxyEq2
  :: (2 <= x)
  => Proxy (((2 ^ x) - 2) * (2 ^ (x + x)))
  -> Proxy ((2 ^ ((x + (x + x)) - 1)) + ((2 ^ ((x + (x + x)) - 1)) - (2 ^ ((x + x) + 1))))
proxyEq2 = id
```
