### ISSUE TITLE
Symbolic arithmetic with type families does not work

### ISSUE THREAD

**Issue by ggreif** [clash-lang/ghc-typelits-natnormalise#7]
```
    Couldn't match type  BitSize Int + BitSize Int 
                   with  2 * BitSize Int 
    Expected type: BitSize (Vec 2 Int)
      Actual type: BitSize (Int, Int)
    In the expression: bitCoerce (2 :: Int, 3 :: Int) :: Vec 2 Int
    In an equation for  it :
        it = bitCoerce (2 :: Int, 3 :: Int) :: Vec 2 Int
```

**Comment by ggreif** [comment]
`BitSize Int` seems to be a little special, because it cannot be evaluated to a constant, as opposed to `BitSize Bool`. To confirm the equation nevertheless, one could come up with a unique variable name (e.g. `uniq`) and replace `BitSize Int` by that. This would change the equation to `(uniq + uniq) ~ (2 * uniq)` which should be easy to solve.

**Comment by christiaanb** [comment]
@ggreif 

If I define the instance:

```haskell
{-# LANGUAGE CPP #-}
#include "MachDeps.h"

instance BitPack Int where
  type BitSize Int = WORD_SIZE_IN_BITS
  pack   = fromIntegral
  unpack = fromIntegral
```

in the clash-prelude (or outside of the clash-prelude with OrphanInstances), everything seems to work:

```
> pack (4 :: Int)
0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0100
> bitCoerce (2 :: Int, 3 :: Int) :: Vec 2 Int
<2,3>
```

And this is using `ghc-typelits-natnormalise-0.4.1`.

**Comment by thoughtpolice** [comment]
I can confirm this works with the latest versions of Clash, as the required instances are available:

```
$ clashi
CLaSHi, version 0.99 (using clash-lib, version 0.99):
http://www.clash-lang.org/  :? for help
CLaSH.Prelude> bitCoerce (2 :: Int, 3 :: Int) :: Vec 2 Int
<2,3>
CLaSH.Prelude> 
```

So this issue can be closed, I think?

**Comment by christiaanb** [comment]
Yes... I also believe that the actual issue was that ghc-typelits-natnormalise reported the complete constraint as unsolvable, because parts of it could not be solved, the `BitSize Int` constraint.

The thing is, the plugin is being overly paranoid, it dictates that every part of the constraint must be solvable, and if individual parts are not, it considers then entire constraint unsolvable. I realise this can lead to confusing error messages, but I'd rather type-check fewer type-correct programs, than accidentally type-check a type-incorrect program.

**Comment by ggreif** [comment]
Yes, CLaSH is not at fault here. The plugin could replace unsolvable type family invocations with a fresh type variable (say `abcd`) and then discover that `(abcd + abcd) ~ (2 * abcd)` is always solvable.
